spring:
  application:
    name: demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest
    virtual-host: /
server:
  port: 8088
  servlet:
    context-path: /demo
  tomcat:
    uri-encoding: UTF-8